# Generated by Django 3.2.8 on 2021-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='visitors_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='visitors_out',
            field=models.IntegerField(default=0),
        ),
    ]
