# Generated by Django 3.2.8 on 2021-11-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20211017_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
